<h1>Linear Regression 1D: Prediction</h1>

In [1]:
# These are the libraries will be used for this lab.

import torch

## Prediction

In [2]:
# Define w = 2 and b = -1 for y = wx + b

w = torch.tensor(2.0, requires_grad = True)
b = torch.tensor(-1.0, requires_grad = True)

<img src="https://ibm.box.com/shared/static/ky0n1mgs378dgw47pmhnqm35mw737fmv.png" width="200" alt="Linear Regression One Input Sample" />

In [3]:
# Function forward(x) for prediction

def forward(x):
    yhat = w * x + b
    return yhat

<img src="https://ibm.box.com/shared/static/keqeopewwwezt09ofpuw17niw0jouock.png" width="200" alt="Linear Regression Prediction on x=1" />

In [4]:
# Predict y = 2x - 1 at x = 1

x = torch.tensor([[1.0]])
yhat = forward(x)
print("The prediction: ", yhat)

The prediction:  tensor([[1.]], grad_fn=<ThAddBackward>)


In [5]:
# Create x Tensor and check the shape of x tensor

x = torch.tensor([[1.0], [2.0]])
print("The shape of x: ", x.shape)

The shape of x:  torch.Size([2, 1])


In [6]:
# Make the prediction of y = 2x - 1 at x = [1, 2]

yhat = forward(x)
print("The prediction: ", yhat)

The prediction:  tensor([[1.],
        [3.]], grad_fn=<ThAddBackward>)


In [8]:
# Practice: Make a prediction of y = 2x - 1 at x = [[1.0], [2.0], [3.0]]

x = torch.tensor([[1.0], [2.0], [3.0]])
yhat = forward(x)
print(yhat)

tensor([[1.],
        [3.],
        [5.]], grad_fn=<ThAddBackward>)


## Class Linear

In [9]:
# Import Class Linear

from torch.nn import Linear

In [10]:
# Set random seed

torch.manual_seed(1)

In [11]:
# Create Linear Regression Model, and print out the parameters

lr = Linear(in_features=1, out_features=1, bias=True)
print("Parameters w and b: ", list(lr.parameters()))

Parameters w and b:  [Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [12]:
# Make the prediction at x = [[1.0]]

x = torch.tensor([[1.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[0.0739]], grad_fn=<ThAddmmBackward>)


In [13]:
# Create the prediction using linear model

x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[0.0739],
        [0.5891]], grad_fn=<ThAddmmBackward>)


In [14]:
# Practice: Use the linear regression model object lr to make the prediction.

x=torch.tensor([[1.0],[2.0],[3.0]])
yhat = lr(x)
print(yhat)

tensor([[0.0739],
        [0.5891],
        [1.1044]], grad_fn=<ThAddmmBackward>)


## Build Custom Modules

In [15]:
# Library for this section

from torch import nn

In [16]:
# Customize Linear Regression Class

class LR(nn.Module):
    
    # Constructor
    def __init__(self, input_size, output_size):
        
        # Inherit from parent
        super(LR, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
    
    # Prediction function
    def forward(self, x):
        out = self.linear(x)
        return out

In [17]:
# Create the linear regression model. Print out the parameters.

lr = LR(1, 1)
print("The parameters: ", list(lr.parameters()))
print("Linear model: ", lr.linear)

The parameters:  [Parameter containing:
tensor([[-0.1939]], requires_grad=True), Parameter containing:
tensor([0.4694], requires_grad=True)]
Linear model:  Linear(in_features=1, out_features=1, bias=True)


In [18]:
# Try our customize linear regression model with single input

x = torch.tensor([[1.0]])
yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[0.2755]], grad_fn=<ThAddmmBackward>)
