<h1 align=center><font size = 5>Multiple Linear Regression</font></h1> 

In [2]:
from torch import nn
import torch
torch.manual_seed(1)

In [3]:
w=torch.tensor([[ 2.0],[3.0]],requires_grad=True)
b=torch.tensor([ [1.0]],requires_grad=True)

In [4]:
def forward(x):
    yhat=torch.mm(x,w)+b
    return yhat

In [5]:
x=torch.tensor([[1.0,2.0]])
yhat=forward(x)
yhat

tensor([[9.]], grad_fn=<ThAddBackward>)

In [6]:
X=torch.tensor([[1.0,1.0],[1.0,2.0],[1.0,3.0]])

In [7]:
yhat=forward(X)
yhat

tensor([[ 6.],
        [ 9.],
        [12.]], grad_fn=<ThAddBackward>)

<a id="ref1"></a>
<h2 align=center>Class Linear  </h2>

In [8]:
model=nn.Linear(2,1)

In [9]:
yhat=model(x)
yhat

tensor([[-0.3969]], grad_fn=<ThAddmmBackward>)

In [10]:
yhat=model(X)
yhat

tensor([[-0.0848],
        [-0.3969],
        [-0.7090]], grad_fn=<ThAddmmBackward>)

<a id="ref2"></a>
<h2 align=center>Build Custom Modules </h2>

In [11]:
class linear_regression(nn.Module):
    def __init__(self,input_size,output_size):
        super(linear_regression,self).__init__()
        self.linear=nn.Linear(input_size,output_size)
    def forward(self,x):
        yhat=self.linear(x)
        return yhat

In [12]:
model=linear_regression(2,1)